/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#4c3500",
        "inverse-primary": "#b0c6ff",
        "on-primary-container": "#7fa1f2",
        "surface-variant": "#e2e2e2",
        "on-primary-fixed": "#001945",
        "secondary": "#0058bc",
        "success-green": "#008009",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#d8e2ff",
        "tertiary": "#302100",
        "on-tertiary-container": "#d19900",
        "inverse-surface": "#2f3131",
        "tertiary-fixed": "#ffdea4",
        "secondary-fixed-dim": "#adc6ff",
        "surface-dim": "#dadada",
        "on-surface-variant": "#434651",
        "inverse-on-surface": "#f1f1f1",
        "on-error-container": "#93000a",
        "outline-variant": "#c4c6d3",
        "surface-container": "#eeeeee",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#b0c6ff",
        "primary-fixed": "#d9e2ff",
        "background-white": "#FFFFFF",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "outline": "#747782",
        "on-background": "#1a1c1c",
        "background": "#f9f9f9",
        "secondary-container": "#1070e8",
        "surface-container-highest": "#e2e2e2",
        "on-secondary-fixed-variant": "#004494",
        "primary": "#002155",
        "surface-tint": "#375ca8",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001a41",
        "on-tertiary-fixed-variant": "#5d4200",
        "tertiary-fixed-dim": "#febb02",
        "on-tertiary-fixed": "#261900",
        "primary-container": "#003580",
        "on-secondary-container": "#fefcff",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        "surface-container-high": "#e8e8e8",
        "on-primary-fixed-variant": "#1a438e",
        "surface-container-low": "#f3f3f3",
        "on-surface": "#1a1c1c",
        "surface": "#f9f9f9",
        "text-main": "#1A1A1A"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "container-max": "1140px",
        "base": "8px",
        "margin-desktop": "24px",
        "margin-mobile": "16px",
        "card-padding": "16px",
        "gutter": "16px"
      },
      fontFamily: {
        "sans": ["Open Sans", "sans-serif"],
        "body-lg": ["Open Sans", "sans-serif"],
        "body-sm": ["Open Sans", "sans-serif"],
        "headline-lg-mobile": ["Open Sans", "sans-serif"],
        "label-bold": ["Open Sans", "sans-serif"],
        "label-caps": ["Open Sans", "sans-serif"],
        "price-display": ["Open Sans", "sans-serif"],
        "headline-lg": ["Open Sans", "sans-serif"],
        "headline-md": ["Open Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
